# Generated by Django 5.1.5 on 2025-03-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('text', models.TextField()),
                ('summary', models.TextField()),
                ('keywords', models.TextField()),
                ('date_published', models.DateField()),
                ('bias', models.CharField(blank=True, choices=[(1, 'Politically Biased'), (0, 'Politically Unbiased')], max_length=10, null=True)),
            ],
        ),
    ]
